"""Plot real ECG examples for each clinical class.

The figures generated by this script are based on the extracted XML
occurrence dataset. No synthetic ECG signals are created here.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOCAL_LIBS = PROJECT_ROOT / ".pythonlibs"

if LOCAL_LIBS.exists():
    sys.path.insert(0, str(LOCAL_LIBS))
    for dll_dir in (
        LOCAL_LIBS / "numpy.libs",
        LOCAL_LIBS / "scipy.libs",
    ):
        if dll_dir.exists() and hasattr(os, "add_dll_directory"):
            os.add_dll_directory(str(dll_dir))

MPL_CONFIG_DIR = PROJECT_ROOT / ".tmp" / "matplotlib"
MPL_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(MPL_CONFIG_DIR))

import numpy as np
from PIL import Image, ImageDraw, ImageFont


LABELS = ["CurrentECG", "AF", "Asystole", "Brady", "VT"]
LABEL_MAP = {
    "CurrentECG": "CurrentECG",
    "AF": "AF",
    "Asystole": "Asystole",
    "Brady": "Brady",
    "VT": "VT",
    "FVT": "VT",
}


def parse_bool(value: str) -> bool:
    return str(value).strip().lower() in {"true", "1", "yes"}


def load_candidate_rows(manifest_path: Path) -> dict[str, list[dict[str, str]]]:
    candidates = {label: [] for label in LABELS}
    with manifest_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            label = LABEL_MAP.get(row["occurrence_type"])
            if label is None:
                continue
            if not parse_bool(row["has_stored_waveform"]):
                continue
            if float(row["sampling_rate_hz"]) != 128.0:
                continue
            if int(row["sample_count"]) < 256:
                continue
            candidates[label].append(row)
    return candidates


def select_examples(rows: list[dict[str, str]], n: int) -> list[dict[str, str]]:
    selected: list[dict[str, str]] = []
    used_devices: set[str] = set()

    for row in rows:
        device_id = row["device_id"]
        if device_id in used_devices:
            continue
        selected.append(row)
        used_devices.add(device_id)
        if len(selected) == n:
            return selected

    for row in rows:
        if row in selected:
            continue
        selected.append(row)
        if len(selected) == n:
            return selected

    return selected


def load_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf"),
        Path("C:/Windows/Fonts/calibrib.ttf" if bold else "C:/Windows/Fonts/calibri.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def scale_points(
    time_seconds: np.ndarray,
    signal: np.ndarray,
    box: tuple[int, int, int, int],
) -> list[tuple[int, int]]:
    left, top, right, bottom = box
    duration = float(time_seconds[-1] - time_seconds[0])
    if duration <= 0:
        duration = 1.0

    y_min = float(np.nanmin(signal))
    y_max = float(np.nanmax(signal))
    if y_min == y_max:
        y_min -= 1.0
        y_max += 1.0
    padding = (y_max - y_min) * 0.12
    y_min -= padding
    y_max += padding

    x = left + ((time_seconds - time_seconds[0]) / duration) * (right - left)
    y = bottom - ((signal - y_min) / (y_max - y_min)) * (bottom - top)
    return [(int(xi), int(yi)) for xi, yi in zip(x, y)], y_min, y_max


def draw_grid(
    draw: ImageDraw.ImageDraw,
    box: tuple[int, int, int, int],
    duration: float,
    y_min: float,
    y_max: float,
    font: ImageFont.ImageFont,
) -> None:
    left, top, right, bottom = box
    grid_color = "#d9dee6"
    axis_color = "#7c8794"
    text_color = "#47515f"

    draw.rectangle(box, outline=axis_color, width=1)
    for i in range(1, 5):
        x = left + int((right - left) * i / 5)
        draw.line([(x, top), (x, bottom)], fill=grid_color, width=1)
    for i in range(1, 4):
        y = top + int((bottom - top) * i / 4)
        draw.line([(left, y), (right, y)], fill=grid_color, width=1)

    zero_y = None
    if y_min <= 0 <= y_max:
        zero_y = bottom - int((0 - y_min) / (y_max - y_min) * (bottom - top))
        draw.line([(left, zero_y), (right, zero_y)], fill="#9aa3ad", width=1)

    tick_values = [0, duration / 2, duration]
    for value in tick_values:
        x = left + int((value / duration) * (right - left)) if duration > 0 else left
        draw.text((x - 18, bottom + 6), f"{value:.1f}s", fill=text_color, font=font)

    draw.text((10, top - 2), f"{y_max:.2f}", fill=text_color, font=font)
    draw.text((10, bottom - 14), f"{y_min:.2f}", fill=text_color, font=font)
    if zero_y is not None:
        draw.text((24, zero_y - 7), "0", fill=text_color, font=font)


def plot_label_examples(label: str, examples: list[dict[str, str]], output_path: Path) -> None:
    width = 1900
    header_height = 90
    panel_height = 285
    footer_height = 55
    height = header_height + panel_height * len(examples) + footer_height

    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    title_font = load_font(34, bold=True)
    subtitle_font = load_font(18, bold=False)
    small_font = load_font(15, bold=False)

    draw.text((35, 24), f"Real ECG examples - {label}", fill="#172033", font=title_font)
    draw.text(
        (35, 62),
        "Signals extracted from XML CardiacOccurrenceRecord arrays; no synthetic examples.",
        fill="#47515f",
        font=subtitle_font,
    )

    for index, row in enumerate(examples, start=1):
        npz_path = PROJECT_ROOT / row["waveform_npz_path"]
        data = np.load(npz_path, allow_pickle=True)
        signal = data["waveform_values"].astype(float)
        time_seconds = data["time_seconds"].astype(float)
        time_seconds = time_seconds - time_seconds[0]

        title = (
            f"{index}. {row['occurrence_id']} | XML: {row['source_xml_name']} | "
            f"{row['sample_count']} samples, {row['sampling_rate_hz']} Hz"
        )
        y0 = header_height + (index - 1) * panel_height
        draw.text((35, y0 + 14), title, fill="#172033", font=small_font)

        plot_box = (85, y0 + 45, width - 35, y0 + panel_height - 38)
        points, y_min, y_max = scale_points(time_seconds, signal, plot_box)
        duration = float(time_seconds[-1] - time_seconds[0])
        draw_grid(draw, plot_box, duration, y_min, y_max, small_font)
        if len(points) > 1:
            draw.line(points, fill="#2456a6", width=2)
        draw.text((35, y0 + 112), "mV", fill="#47515f", font=small_font)

    draw.text(
        (width // 2 - 160, height - 42),
        "Seconds from start of stored waveform",
        fill="#47515f",
        font=subtitle_font,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(output_path)


def write_selection_csv(path: Path, selected: dict[str, list[dict[str, str]]]) -> None:
    fields = [
        "plotted_label",
        "original_occurrence_type",
        "occurrence_id",
        "source_xml_name",
        "source_xml_path",
        "device_id",
        "occurrence_datetime",
        "sampling_rate_hz",
        "sample_count",
        "waveform_duration_seconds",
        "waveform_npz_path",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for label, rows in selected.items():
            for row in rows:
                writer.writerow(
                    {
                        "plotted_label": label,
                        "original_occurrence_type": row["occurrence_type"],
                        "occurrence_id": row["occurrence_id"],
                        "source_xml_name": row["source_xml_name"],
                        "source_xml_path": row["source_xml_path"],
                        "device_id": row["device_id"],
                        "occurrence_datetime": row["occurrence_datetime"],
                        "sampling_rate_hz": row["sampling_rate_hz"],
                        "sample_count": row["sample_count"],
                        "waveform_duration_seconds": row["waveform_duration_seconds"],
                        "waveform_npz_path": row["waveform_npz_path"],
                    }
                )


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot real ECG examples by class.")
    parser.add_argument(
        "--manifest-path",
        type=Path,
        default=PROJECT_ROOT / "data/processed/occurrence_dataset/occurrences_manifest.csv",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "reports/iteration_1/ecg_examples",
    )
    parser.add_argument("--examples-per-class", type=int, default=5)
    args = parser.parse_args()

    candidates = load_candidate_rows(args.manifest_path)
    selected = {
        label: select_examples(candidates[label], args.examples_per_class)
        for label in LABELS
    }

    for label, rows in selected.items():
        if len(rows) < args.examples_per_class:
            raise RuntimeError(
                f"Only found {len(rows)} usable examples for {label}; "
                f"{args.examples_per_class} required."
            )
        plot_label_examples(label, rows, args.output_dir / f"{label}_examples.png")

    write_selection_csv(args.output_dir / "selected_real_ecg_examples.csv", selected)

    print("Generated real ECG example figures:")
    for label in LABELS:
        print(f"- {label}: {args.output_dir / f'{label}_examples.png'}")
    print(f"Selection CSV: {args.output_dir / 'selected_real_ecg_examples.csv'}")


if __name__ == "__main__":
    main()
